Refactor branch options in test_release.yml
Updated branch options and conditions for KernelSU variant handling in the GitHub Actions workflow.

diff --git a/.github/workflows/test_release.yml b/.github/workflows/test_release.yml
--- a/.github/workflows/test_release.yml
+++ b/.github/workflows/test_release.yml
@@ -30,9 +30,9 @@ on:
         required: true
         type: choice
         options:
-          - Stable(Standard)
-          - Dev(Development)
-          - Other(Other/Custom)
+          - Stable
+          - Dev
+          - Other
         default: Dev(Development)
 
       # kernelsu_branch_other:
@@ -110,7 +110,7 @@ jobs:
         Included: **${{ inputs.kernelsu_variant == 'Next' && 'KernelSU-' || '' }}${{ inputs.kernelsu_variant }}**、SUSFS ${{ needs.get_manager.outputs.susVer }}${{ inputs.use_zram && ', LZ4KD' || '' }}
 
         Features:
-        -> ${{ inputs.kernelsu_variant == 'Next' && 'KernelSU-' || '' }}${{ inputs.kernelsu_variant }}${{ inputs.kernelsu_variant == 'Official' && 'Original' || '' }}${{ inputs.kernelsu_branch == 'Dev(Development)' && format('({0})', needs.get_manager.outputs.ksuVer) || 'Stable' }}
+        -> ${{ inputs.kernelsu_variant == 'Next' && 'KernelSU-' || '' }}${{ inputs.kernelsu_variant }}${{ inputs.kernelsu_variant == 'Official' && 'Original' || '' }}${{ inputs.kernelsu_branch == 'Dev' && format('({0})', needs.get_manager.outputs.ksuVer) || 'Stable' }}
         -> SUSFS ඞ ${{ needs.get_manager.outputs.susVer }}
         -> SUSFS Inline Hooks
         ${{ inputs.kernelsu_variant != 'Official' && '-> Magic Mount Support' || '-> OVERLAYFS Support' }}
@@ -127,7 +127,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Determine branch for KernelSU-${{ inputs.kernelsu_variant }}
-        if: ${{ inputs.kernelsu_branch == 'Dev(Development)' || inputs.kernelsu_variant == 'MKSU' || inputs.kernelsu_variant == 'SukiSU' }}
+        if: ${{ inputs.kernelsu_branch == 'Dev' || inputs.kernelsu_variant == 'MKSU' || inputs.kernelsu_variant == 'SukiSU' }}
         run: |
           if [[ "${{ inputs.kernelsu_variant }}" == "Official" || "${{ inputs.kernelsu_variant }}" == "MKSU" ]]; then
             BRANCH="main"
@@ -163,7 +163,7 @@ jobs:
             echo "Unknown variant"
           fi
 
-          if [[ "${{ inputs.kernelsu_branch }}" == "Stable(Standard)" && "${{ inputs.kernelsu_variant }}" != "MKSU" ]]; then
+          if [[ "${{ inputs.kernelsu_branch }}" == "Stable" && "${{ inputs.kernelsu_variant }}" != "MKSU" ]]; then
             # Fetch the latest tag
             TAG=$(git ls-remote --tags --sort=-v:refname $REPO_URL | grep -o 'refs/tags/.*' | cut -d'/' -f3 | head -n1)
             if [[ -z "$TAG" ]]; then
@@ -173,11 +173,11 @@ jobs:
             KSU_REF=$TAG
             KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
 
-          elif [[ "${{ inputs.kernelsu_branch }}" == "Dev(Development)" || "${{ inputs.kernelsu_variant }}" == "MKSU" || "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
+          elif [[ "${{ inputs.kernelsu_branch }}" == "Dev" || "${{ inputs.kernelsu_variant }}" == "MKSU" || "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
             # Fetch the latest commit from branch
             COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$KSU_BRANCH | awk '{ print $1 }')
             if [[ -z "$COMMIT_HASH" ]]; then
-              echo "Error: Could not fetch latest commit for Dev(Development)" >&2
+              echo "Error: Could not fetch latest commit for Dev" >&2
               exit 1
             fi
             KSU_REF=$COMMIT_HASH
@@ -264,7 +264,7 @@ jobs:
           echo "<summary>Commit Information</summary>" >> $GITHUB_ENV
           echo "" >> $GITHUB_ENV
           echo "Commit hashes and links (the following commits refer to the KSU or SUSFS state used during this build):" >> $GITHUB_ENV
-          echo "- **KernelSU ${{ inputs.kernelsu_variant == 'Next' && 'KernelSU-' || '' }}${{ inputs.kernelsu_variant }}${{ inputs.kernelsu_branch == 'Dev(开发)' && format('({0})', needs.get_manager.outputs.ksuVer) || 'Stable' }}** (commit): [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
+          echo "- **KernelSU ${{ inputs.kernelsu_variant == 'Next' && 'KernelSU-' || '' }}${{ inputs.kernelsu_variant }}${{ inputs.kernelsu_branch == 'Dev' && format('({0})', needs.get_manager.outputs.ksuVer) || 'Stable' }}** (commit): [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
           echo "- **SUSFS4KSU** (commits):" >> $GITHUB_ENV
           echo "  - gki-android12-5.10: [$COMMIT_HASH_gki_android12_5_10]($COMMIT_URL_gki_android12_5_10)" >> $GITHUB_ENV
           echo "  - gki-android13-5.10: [$COMMIT_HASH_gki_android13_5_10]($COMMIT_URL_gki_android13_5_10)" >> $GITHUB_ENV
